[repository]
name = "hyprsquint"
authors = ["slothsh"]
commit_pins = [
    ["0f594732b063a90d44df8c5d402d658f27471dfe", "cad9bab701a5ec1e05c356b2c058784b45134a84"]
]

[hyprsquint]
description = "A Hyprland plugin for magnifying your screen."
authors = ["slothsh"]
output = "build/hyprsquint.so"
build = [
    "bash build.sh"
]
